services:
  postgres:
    image: postgres:17-alpine
    container_name: cvms-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cvms
      POSTGRES_USER: cvms_user
      POSTGRES_PASSWORD: cvms_password

    ports:
      - "5431:5432"

    volumes:
      - cvms_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cvms_user -d cvms"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17.0
    container_name: cvms-odoo
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    command: --db-filter=^odoo_db$
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./odoo-custom-addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    environment:
      - HOST=postgres
      - USER=cvms_user
      - PASSWORD=cvms_password

volumes:
  cvms_postgres_data:
  odoo_data: