FROM odoo:17.0
COPY ./odoo-custom-addons /mnt/extra-addons

USER root
# Delete the entire block that checks for postgres user
RUN sed -i '/security risk/,+2d' /entrypoint.sh || true
RUN sed -i 's/exit 1/echo bypass/g' /entrypoint.sh || true
USER odoo

