name: CI

on:
  push: 
    branches:
      - main
      - dev
  pull_request: 
    branches:
      - main
      - dev

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.401"
        
      - name: Restore
        run: dotnet restore CVMS.slnx
        
      - name: Build
        run: dotnet build CVMS.slnx --configuration Release --no-restore
        
      - name: Test
        run: dotnet test CVMS.slnx --configuration Release --no-build
        
      - name: Build Docker iamge
        run: docker build -t cvms:${{github.sha}} .